### ISSUE TITLE
Gem update fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by fasmat** [ruby/readline-ext#7]
When I try to update readline-ext on Ubuntu 20.04 I receive the following error:

```
Updating readline-ext
Building native extensions. This could take a while...
ERROR:  Error installing readline-ext:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/readline-ext-0.1.2/ext/readline
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20210719-6663-inf6cb.rb extconf.rb
checking for tgetnum() in -lncurses... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
	--with-curses-dir
	--without-curses-dir
	--with-curses-include
	--without-curses-include=${curses-dir}/include
	--with-curses-lib
	--without-curses-lib=${curses-dir}/lib
	--with-ncurses-dir
	--without-ncurses-dir
	--with-ncurses-include
	--without-ncurses-include=${ncurses-dir}/include
	--with-ncurses-lib
	--without-ncurses-lib=${ncurses-dir}/lib
	--with-termcap-dir
	--without-termcap-dir
	--with-termcap-include
	--without-termcap-include=${termcap-dir}/include
	--with-termcap-lib
	--without-termcap-lib=${termcap-dir}/lib
	--with-readline-dir
	--without-readline-dir
	--with-readline-include
	--without-readline-include=${readline-dir}/include
	--with-readline-lib
	--without-readline-lib=${readline-dir}/lib
	--enable-libedit
	--disable-libedit
	--with-ncurseslib
	--without-ncurseslib
/usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /usr/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /usr/lib/ruby/2.7.0/mkmf.rb:794:in `try_func'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1029:in `block in have_library'
	from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1024:in `have_library'
	from extconf.rb:34:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/readline-ext-0.1.2/mkmf.log

extconf failed, exit code 1
```

mkmf.log:

```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.7.0 -I/usr/include/ruby-2.7.0/ruby/backward -I/usr/include/ruby-2.7.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/ruby2.7-2E2p8v/ruby2.7-2.7.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby-2.7  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

libncurses-dev is installed on my system. What else could the issue be?

**Comment by nobu** [comment]
Is ruby-dev installed?

**Comment by fasmat** [comment]
> Is ruby-dev installed?

Yes, and up to date

**Comment by nobu** [comment]
The building log fails at `have_library`, but that mkmf.log is only for `have_devel?`.
I suspect it isn't the right log file.

**Comment by fasmat** [comment]
What do you mean with not the right log file?

**Comment by nobu** [comment]
I'm afraid that it isn't `/var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/readline-ext-0.1.2/mkmf.log` file.

**Comment by fasmat** [comment]
![screenshot](https://user-images.githubusercontent.com/5011972/136769819-6ca41a52-f89e-4df7-9abf-6deed5f7ff49.png)

**Comment by fasmat** [comment]
Due to an unrelated issue I completely reinstalled Ubuntu 20.04 today and reinstalled all gems that I need, including `readline-ext`. I now have the most recent version (0.1.2) and `gem update` doesn't give me the error above any more.

I don't know what caused the issue, but since it now disappeared we can close this issue.
